version: '3.7'

services:
  torchserve-mar:
    build: server/
    ports:
      - "8080:8080"
      - "8081:8081" 
    volumes:
      - ./:/codes
  xrayapp:
    build: client/
    ports:
      - "9696:9696"
